# Generated by Django 3.1.1 on 2020-09-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200927_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
